{
 "title": "Firewall - Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Elasticsearch", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "PASS - Firewall events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1395",
       "fake": true,
       "field": "event.action",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:518",
       "field": "event.action.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event.action:pass",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 0 },
   "options": {
    "content": "<img src=\"https://opnsense.org/wp-content/themes/OPNsense/assets/img/xopnsense.png.pagespeed.ic.l-2rAT7LtW.png\" >\n         "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BLOCK - Firewall events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1395",
       "fake": true,
       "field": "event.action",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:518",
       "field": "event.action.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event.action:block",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Map - Destination",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 5 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3255",
       "field": "destination.geo.location",
       "id": "2",
       "settings": { "precision": 3 },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3135",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Map - Source",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 5 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3255",
       "field": "source.geo.location",
       "id": "2",
       "settings": { "precision": 3 },
       "type": "geohash_grid"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:3135",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Event Type Over Time",
   "type": "graph",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:710",
       "fake": true,
       "field": "event.action",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:600",
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:701", "field": "select field", "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Events by Interface",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 16, "w": 4, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:862",
       "fake": true,
       "field": "event.action",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:76",
       "fake": true,
       "field": "interface.alias",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:710",
       "fake": true,
       "field": "@timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:701", "field": "select field", "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Country Destination Tags",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:54",
       "fake": true,
       "field": "destination.geo.country_name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:52",
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Country Source Tags",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:54",
       "fake": true,
       "field": "source.geo.country_name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:52",
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Transport Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:862",
       "fake": true,
       "field": "network.transport",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:710",
       "fake": true,
       "field": "@timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:701", "field": "select field", "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Discover",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:7864",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:7862",
       "field": "select metric",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "logs"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Events by Interface",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:862",
       "fake": true,
       "field": "interface.alias",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:710",
       "fake": true,
       "field": "@timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:701", "field": "select field", "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Country Destination/Time",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:710",
       "fake": true,
       "field": "destination.geo.country_name",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:600",
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:701", "field": "select field", "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Country Source/Time",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:710",
       "fake": true,
       "field": "source.geo.country_name",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:600",
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:701", "field": "select field", "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network/Organization Name",
   "type": "grafana-sankey-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:713",
       "fake": true,
       "field": "network.name",
       "id": "6",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:710",
       "fake": true,
       "field": "destination.as.organization.name",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:600",
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:701", "field": "select field", "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}