{
 "title": "Firewall - Unbound",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Elasticsearch", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://opnsense.org/wp-content/themes/OPNsense/assets/img/xopnsense.png.pagespeed.ic.l-2rAT7LtW.png\" >\n         "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 10 Client IPs",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:54",
       "fake": true,
       "field": "client.ip",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:52",
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 10 URLs",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:54",
       "fake": true,
       "field": "dns.question.name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:52",
       "field": "even",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network/Organization Name",
   "type": "graph",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:713",
       "fake": true,
       "field": "client.ip",
       "id": "6",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:710",
       "fake": true,
       "field": "dns.question.name",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:600",
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:701", "field": "select field", "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network/Organization Name",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:713",
       "fake": true,
       "field": "client.ip",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:600",
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:701", "field": "select field", "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Discover",
   "type": "table",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:7864",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:7862",
       "field": "select metric",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "logs"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Answer Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:862",
       "fake": true,
       "field": "dns.answers.type",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:710",
       "fake": true,
       "field": "@timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:701", "field": "select field", "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Client IP/Time",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:713",
       "fake": true,
       "field": "client.ip",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:600",
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:701", "field": "select field", "id": "4", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}